[build-system]
requires=["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name="mictlanx"
version="0.0.29"
authors=[{name="Nacho Castillo", email="jesus.castillo.b@cinvestav.mx"}]
description = "Client to connect to MictlanX storage system"
readme ="README.md"
dependencies=["numpy","retry","option","python-magic","nanoid","python-dotenv","python-lfu","durations"]
[project.urls]
"Github" = "https://github.com/nachocodexx/mictlanx-client"
[tool.setuptools.packages.find]
where   = ["src"]
include=[
    "mictlanx",
    "mictlanx.v3",
    "mictlanx.interfaces",
    "mictlanx.interfaces.v3",
    "mictlanx.logger",
    "mictlanx.utils",
    "mictlanx.v2",
    "mictlanx.v2.interfaces",
    "mictlanx.v2.codec",
    "mictlanx.v2.constants",
    "mictlanx.v2.services",
    "mictlanx.v3.interfaces",
    "mictlanx.v3.services",
]
namespaces = true  # true by default
