[build-system]
requires=["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name="mictlanx"
version="0.0.57"
authors=[{name="Nacho Castillo", email="jesus.castillo.b@cinvestav.mx"}]
description = "Client to perform operation in the MictlanX storage system"
readme ="README.md"
dependencies=[
    "numpy==1.23.2",
    "retry==0.9.2",
    "option==2.1.0",
    "python-magic==0.4.27",
    "nanoid==2.0.0",
    "python-dotenv==1.0.0",
    "python-lfu==0.0.1",
    "durations==0.3.3",
    "cryptography==39.0.2",
    "pycryptodome==3.17",
    "ipaddress==1.0.23"
]
[project.urls]
"Github" = "https://github.com/nachocodexx/mictlanx-client"
[tool.setuptools.packages.find]
where   = ["src"]
include=[
    "mictlanx",
    "mictlanx.v3",
    "mictlanx.interfaces",
    "mictlanx.interfaces.v3",
    "mictlanx.logger",
    "mictlanx.utils",
    "mictlanx.v2",
    "mictlanx.v2.interfaces",
    "mictlanx.v2.codec",
    "mictlanx.v2.constants",
    "mictlanx.v2.services",
    "mictlanx.v3.interfaces",
    "mictlanx.v3.services",
    "mictlanx.v4",
    "mictlanx.v4.xolo",
    "mictlanx.v4.interfaces",
]
namespaces = true  # true by default
