[tool.poetry]
name = "mictlanx"
version = "0.0.160-alpha.3"
description = "MictlanX Client - safely store your data and access them from any application"
authors = ["Ignacio Castillo <ignacio.bcastillo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4"
ipaddress = "^1.0.23"
nanoid = "^2.0.0"
option = "^2.1.0"
requests = "^2.31.0"
retry = "^0.9.2"
humanfriendly = "^10.0"
httpx = "*"
xolo = { version = "^0.0.7", source = "test" }
numpy = ">=1.21.0,<=1.26.0"
pyparsing = "^3.1.2"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pandas = "*"
scipy = "*"
python-dotenv = "^1.0.1"

mkdocs = "^1.6.0"
mkdocstrings = {extras = ["python"], version = "^0.25.1"}
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
priority = "supplemental"
