[tool.poetry]
name = "mictlanx"
version = "0.0.149"
description = "Client to perform operation in the MictlanX storage system"
authors = ["Ignacio Castillo <ignacio.bcastillo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
# durations = "^0.3.3"
durations = "*"
ipaddress = "^1.0.23"
nanoid = "^2.0.0"
option = "^2.1.0"
python-dotenv = "^1.0.1"
requests = "^2.31.0"
retry = "^0.9.2"
humanfriendly = "^10.0"
httpx = "*"
cryptography = "^42.0.5"
pycryptodome = "^3.20.0"
xolo = {version = "^0.0.7", source = "test"}
numpy = "*"
pyparsing = "^3.1.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
# pandas = "*"
# scipy = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
priority = "supplemental"


[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/legacy/"
priority = "primary"

