name: Python package
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Build and publish MictlanX - Client
          uses: JRubics/poetry-publish@v2.0
          with:
                python_version: "3.8"
                poetry_version: "==1.8.2" # (PIP version specifier syntax)
                pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
                build_format: "sdist"
                allow_poetry_pre_release: "yes"
                repository_name: "testpypi"
                repository_url: "https://test.pypi.org/legacy/"